export const CREATE_CHECK = 'CREATE_CHECK';
export const CREATE_EQUIP = 'CREATE_EQUIP';
export const EDIT_EQUIP = 'EDIT_EQUIP';
export const DELETE_EQUIP = 'DELETE_EQUIP';
export const CREATE_CHECKLIST = 'CREATE_CHECKLIST';
export const EDIT_CHECKLIST = 'EDIT_CHECKLIST';
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST';
